---
- name: lxd - ensure sync_base_url is in /etc/ego.conf
  ansible.builtin.lineinfile:
    path: /etc/ego.conf
    line: 'sync_base_url=https://github.com/funtoo-repo/{repo}'
    create: yes
    state: present
  register: out
- debug: var=out.stdout_lines

- name: lxd - ensure GENTOO_MIRRORS is in /etc/portage/make.conf
  ansible.builtin.lineinfile:
    path: /etc/portage/make.conf
    line: 'GENTOO_MIRRORS=https://direct-github.funmore.org'
    create: yes
    state: present
  register: out
- debug: var=out.stdout_lines

- name: lxd - ensure app-emulation/lxd is installed
  portage:
    package: app-emulation/lxd
    state: present
  register: out
- debug: var=out.stdout_lines

- name: lxd - ensure dev-python/python3-lxc is installed
  portage:
    package: dev-python/python3-lxc
    state: present
  register: out
- debug: var=out.stdout_lines
