---
- name: regen-nginx - create self signed cert
  command: >
    openssl req -x509 -nodes -subj '/CN={{ container_name }}' -addext 'subjectAltName=DNS:{{ container_name }},IP:{{ ansible_host }}' -days 3650 -newkey rsa:4096 -sha256 -keyout /etc/ssl/private/server.key -out /etc/ssl/certs/server.crt
    creates=/etc/ssl/certs/server.crt
