---
- name: repo - ensure sync_base_url is in /etc/ego.conf
  ansible.builtin.lineinfile:
    path: /etc/ego.conf
    line: 'sync_base_url=https://github.com/funtoo-repo/{repo}'
    create: yes
    state: present
  register: out
- debug: var=out.stdout_lines

- name: repo - ensure GENTOO_MIRRORS is in /etc/portage/make.conf
  ansible.builtin.lineinfile:
    path: /etc/portage/make.conf
    line: 'GENTOO_MIRRORS=https://direct-github.funmore.org'
    create: yes
    state: present
  register: out
- debug: var=out.stdout_lines

- name: repo - ego sync
  shell: |
    /usr/bin/ego sync
  register: out
- debug: var=out.stdout_lines

- name: repo - ensure www-apps/gitea is installed
  portage:
    package: www-apps/gitea
    state: present
    quiet: true
  register: out
- debug: var=out.stdout_lines


