---
- name: repo - create repos
  become: true
  become_user: "{{ gitea_user }}"
  become_method: su
  become_flags: '--login'
  command: >
    /usr/bin/curl 
      -k
      -X 'POST'
      'https://{{ ansible_host }}/api/v1/org/auto/repos' 
      -H "content-type: application/json" 
      -H "Authorization: token {{ gitea_repo_user_token }}" 
      -d '{
        "name": "{{ item }}" 
      }'
  with_items:
    - browser-kit
    - core-gl-kit
    - core-hw-kit
    - core-kit
    - core-server-kit
    - dev-kit
    - desktop-kit
    - editors-kit
    - games-kit
    - gnome-kit
    - haskell-kit
    - i18n-kit
    - java-kit
    - kde-kit
    - lang-kit
    - llvm-kit
    - lisp-scheme-kit
    - mate-kit
    - media-kit
    - meta-repo
    - ml-lang-kit
    - net-kit
    - perl-kit
    - python-kit
    - python-modules-kit
    - qt-kit
    - ruby-kit
    - science-kit
    - security-kit
    - text-kit
    - xfce-kit
  register: out
- debug: var=out.stdout_lines