---
- name: repo - create repos
  become: true
  become_user: "{{ gitea_user }}"
  become_method: su
  become_flags: '--login'
  command: >
    /usr/bin/curl 
      -k 
      -X 'POST'
      'https://{{ ansible_host }}/api/v1/repos/migrate' 
      -H "content-type: application/json"  
      -H "Authorization: token {{ gitea_repo_user_token }}"
      -d '{
        "clone_addr": "{{ item.url }}",
        "repo_name": "{{ item.repo_name }}",
        "repo_owner": "{{ item.repo_owner }}",
        "mirror": true,
        "service": "git"
      }'
  with_items:
    - { url: "https://github.com/funtoo-src/appi.git", repo_name: "appi", repo_owner: "funtoo-src" }
    - { url: "https://github.com/funtoo-src/baselayout.git", repo_name: "baselayout", repo_owner: "funtoo-src" }
    - { url: "https://github.com/funtoo-src/boot-update.git", repo_name: "boot-update", repo_owner: "funtoo-src" }
    - { url: "https://github.com/funtoo-src/corenetwork.git", repo_name: "corenetwork", repo_owner: "funtoo-src" }
    - { url: "https://github.com/funtoo-src/ego.git", repo_name: "ego", repo_owner: "funtoo-src" }
    - { url: "https://github.com/funtoo-src/ffs.git", repo_name: "ffs", repo_owner: "funtoo-src" }
    - { url: "https://github.com/funtoo-src/funtoo-stig.git", repo_name: "funtoo-stig", repo_owner: "funtoo-src" }
    - { url: "https://github.com/funtoo-src/gnome-kit-sources.git", repo_name: "gnome-kit-sources", repo_owner: "funtoo-src" }
    - { url: "https://github.com/funtoo-src/i18n-kit-sources.git", repo_name: "i18n-kit-sources", repo_owner: "funtoo-src" }
    - { url: "https://github.com/funtoo-src/kde-kit-sources.git", repo_name: "kde-kit-sources", repo_owner: "funtoo-src" }
    - { url: "https://github.com/funtoo-src/kit-fixups.git", repo_name: "kit-fixups", repo_owner: "funtoo-src" }
    - { url: "https://github.com/funtoo-src/mate-kit-sources.git", repo_name: "mate-kit-sources", repo_owner: "funtoo-src" }
    - { url: "https://github.com/funtoo-src/merge-scripts.git", repo_name: "merge-scripts", repo_owner: "funtoo-src" }
    - { url: "https://github.com/funtoo-src/metro.git", repo_name: "metro", repo_owner: "funtoo-src" }
    - { url: "https://github.com/funtoo-src/openrc.git", repo_name: "openrc", repo_owner: "funtoo-src" }
    - { url: "https://github.com/funtoo-src/perl-kit-sources.git", repo_name: "perl-kit-sources", repo_owner: "funtoo-src" }
    - { url: "https://github.com/funtoo-src/qt-kit-sources.git", repo_name: "qt-kit-sources", repo_owner: "funtoo-src" }
    - { url: "https://github.com/funtoo-src/realdev.git", repo_name: "realdev", repo_owner: "funtoo-src" }
    - { url: "https://github.com/funtoo-src/xfce-kit-sources.git", repo_name: "xfce-kit-sources", repo_owner: "funtoo-src" }
    - { url: "https://github.com/funtoo-src/flora.git", repo_name: "flora", repo_owner: "funtoo-co-src" }
    - { url: "https://github.com/funtoo-src/ncse-overlay.git", repo_name: "ncse-overlay", repo_owner: "funtoo-co-src" }
    - { url: "https://github.com/funtoo-repo/skeleton-overlay.git", repo_name: "skeleton-overlay", repo_owner: "funtoo-co-src" }
    - { url: "https://github.com/funtoo-repo/browser-kit.git", repo_name: "browser-kit", repo_owner: "funtoo-repo" }
    - { url: "https://github.com/funtoo-repo/core-gl-kit.git", repo_name: "core-gl-kit", repo_owner: "funtoo-repo" }
    - { url: "https://github.com/funtoo-repo/core-hw-kit.git", repo_name: "core-hw-kit", repo_owner: "funtoo-repo" }
    - { url: "https://github.com/funtoo-repo/core-kit.git", repo_name: "core-kit", repo_owner: "funtoo-repo" }
    - { url: "https://github.com/funtoo-repo/core-server-kit.git", repo_name: "core-server-kit", repo_owner: "funtoo-repo" }
    - { url: "https://github.com/funtoo-repo/core-ui-kit.git", repo_name: "core-ui-kit", repo_owner: "funtoo-repo" }
    - { url: "https://github.com/funtoo-repo/desktop-kit.git", repo_name: "desktop-kit", repo_owner: "funtoo-repo" }
    - { url: "https://github.com/funtoo-repo/dev-kit.git", repo_name: "dev-kit", repo_owner: "funtoo-repo" }
    - { url: "https://github.com/funtoo-repo/editors-kit.git", repo_name: "editors-kit", repo_owner: "funtoo-repo" }
    - { url: "https://github.com/funtoo-repo/games-kit.git", repo_name: "games-kit", repo_owner: "funtoo-repo" }
    - { url: "https://github.com/funtoo-repo/gentoo-staging.git", repo_name: "gentoo-staging", repo_owner: "funtoo-repo" }
    - { url: "https://github.com/funtoo-repo/gnome-kit.git", repo_name: "gnome-kit", repo_owner: "funtoo-repo" }
    - { url: "https://github.com/funtoo-repo/haskell-kit.git", repo_name: "haskell-kit", repo_owner: "funtoo-repo" }
    - { url: "https://github.com/funtoo-repo/i18n-kit.git", repo_name: "i18n-kit", repo_owner: "funtoo-repo" }
    - { url: "https://github.com/funtoo-repo/java-kit.git", repo_name: "java-kit", repo_owner: "funtoo-repo" }
    - { url: "https://github.com/funtoo-repo/kde-kit.git", repo_name: "kde-kit", repo_owner: "funtoo-repo" }
    - { url: "https://github.com/funtoo-repo/lang-kit.git", repo_name: "lang-kit", repo_owner: "funtoo-repo" }
    - { url: "https://github.com/funtoo-repo/lisp-scheme-kit.git", repo_name: "lisp-scheme-kit", repo_owner: "funtoo-repo" }
    - { url: "https://github.com/funtoo-repo/llvm-kit.git", repo_name: "llvm-kit", repo_owner: "funtoo-repo" }
    - { url: "https://github.com/funtoo-repo/mate-kit.git", repo_name: "mate-kit", repo_owner: "funtoo-repo" }
    - { url: "https://github.com/funtoo-repo/media-kit.git", repo_name: "media-kit", repo_owner: "funtoo-repo" }
    - { url: "https://github.com/funtoo-repo/meta-repo.git", repo_name: "meta-repo", repo_owner: "funtoo-repo" }
    - { url: "https://github.com/funtoo-repo/ml-lang-kit.git", repo_name: "ml-lang-kit", repo_owner: "funtoo-repo" }
    - { url: "https://github.com/funtoo-repo/net-kit.git", repo_name: "net-kit", repo_owner: "funtoo-repo" }
    - { url: "https://github.com/funtoo-repo/nokit.git", repo_name: "nokit", repo_owner: "funtoo-repo" }
    - { url: "https://github.com/funtoo-repo/perl-kit.git", repo_name: "perl-kit", repo_owner: "funtoo-repo" }
    - { url: "https://github.com/funtoo-repo/php-kit.git", repo_name: "php-kit", repo_owner: "funtoo-repo" }
    - { url: "https://github.com/funtoo-repo/python-kit.git", repo_name: "python-kit", repo_owner: "funtoo-repo" }
    - { url: "https://github.com/funtoo-repo/python-modules-kit.git", repo_name: "python-modules-kit", repo_owner: "funtoo-repo" }
    - { url: "https://github.com/funtoo-repo/qt-kit.git", repo_name: "qt-kit", repo_owner: "funtoo-repo" }
    - { url: "https://github.com/funtoo-repo/ruby-kit.git", repo_name: "ruby-kit", repo_owner: "funtoo-repo" }
    - { url: "https://github.com/funtoo-repo/science-kit.git", repo_name: "science-kit", repo_owner: "funtoo-repo" }
    - { url: "https://github.com/funtoo-repo/security-kit.git", repo_name: "security-kit", repo_owner: "funtoo-repo" }
    - { url: "https://github.com/funtoo-repo/text-kit.git", repo_name: "text-kit", repo_owner: "funtoo-repo" }
    - { url: "https://github.com/funtoo-repo/xfce-kit.git", repo_name: "xfce-kit", repo_owner: "funtoo-repo" }
    - { url: "https://github.com/funtoo-src/aiohttp.git", repo_name: "aiohttp", repo_owner: "funtoo-misc-src" }
    - { url: "https://github.com/funtoo-src/dapper.git", repo_name: "dapper", repo_owner: "funtoo-misc-src" }
    - { url: "https://github.com/funtoo-src/dropbox-python-setup.git", repo_name: "dropbox-python-setup", repo_owner: "funtoo-misc-src" }
    - { url: "https://github.com/funtoo-src/eudev.git", repo_name: "eudev", repo_owner: "funtoo-misc-src" }
    - { url: "https://github.com/funtoo-src/genkernel.git", repo_name: "genkernel", repo_owner: "funtoo-misc-src" }
    - { url: "https://github.com/funtoo-src/genkernel-funtoo.git", repo_name: "genkernel-funtoo", repo_owner: "funtoo-misc-src" }
    - { url: "https://github.com/funtoo/keychain.git", repo_name: "keychain", repo_owner: "funtoo-misc-src" }
    - { url: "https://github.com/funtoo-src/lxcfs.git", repo_name: "lxcfs", repo_owner: "funtoo-misc-src" }
    - { url: "https://github.com/funtoo-src/openrazer.git", repo_name: "openrazer", repo_owner: "funtoo-misc-src" }
    - { url: "https://github.com/funtoo-src/portage-classic.git", repo_name: "portage-classic", repo_owner: "funtoo-misc-src" }
    - { url: "https://github.com/funtoo-src/portage-funtoo.git", repo_name: "portage-funtoo", repo_owner: "funtoo-misc-src" }
    - { url: "https://github.com/funtoo-src/portage-gentoo.git", repo_name: "portage-gentoo", repo_owner: "funtoo-misc-src" }
    - { url: "https://github.com/funtoo-src/spl.git", repo_name: "spl", repo_owner: "funtoo-misc-src" }
    - { url: "https://github.com/funtoo-src/xkernel.git", repo_name: "xkernel", repo_owner: "funtoo-misc-src" }
    - { url: "https://github.com/funtoo-src/zfs.git", repo_name: "zfs", repo_owner: "funtoo-misc-src" }
    - { url: "https://github.com/funtoo-src/drobbins-core-gl-testkit.git", repo_name: "drobbins-core-gl-testkit", repo_owner: "funtoo-drobbins-src" }
    - { url: "https://github.com/funtoo-src/drobbins-dockerize.git", repo_name: "drobbins-dockerize", repo_owner: "funtoo-drobbins-src" }
    - { url: "https://github.com/funtoo-src/drobbins-fchroot.git", repo_name: "drobbins-fchroot", repo_owner: "funtoo-drobbins-src" }
    - { url: "https://github.com/funtoo-src/drobbins-flora-dr.git", repo_name: "drobbins-flora-dr", repo_owner: "funtoo-drobbins-src" }
    - { url: "https://github.com/funtoo-src/drobbins-funtoo-metatools.git", repo_name: "drobbins-funtoo-metatools", repo_owner: "funtoo-drobbins-src" }
    - { url: "https://github.com/funtoo-src/drobbins-funtoo-ramdisk.git", repo_name: "drobbins-funtoo-ramdisk", repo_owner: "funtoo-drobbins-src" }
    - { url: "https://github.com/funtoo-src/drobbins-funtoo-sec.git", repo_name: "drobbins-funtoo-sec", repo_owner: "funtoo-drobbins-src" }
    - { url: "https://github.com/funtoo-src/drobbins-funtoo-test-suite.git", repo_name: "drobbins-funtoo-test-suite", repo_owner: "funtoo-drobbins-src" }
    - { url: "https://github.com/funtoo-src/drobbins-kit-fixups.git", repo_name: "drobbins-kit-fixups", repo_owner: "funtoo-drobbins-src" }
    - { url: "https://github.com/funtoo-src/drobbins-metarepo-mirror.git", repo_name: "drobbins-metarepo-mirror", repo_owner: "funtoo-drobbins-src" }
    - { url: "https://github.com/funtoo-src/drobbins-python-kit-dr.git", repo_name: "drobbins-python-kit-dr", repo_owner: "funtoo-drobbins-src" }
    - { url: "https://github.com/funtoo-src/drobbins-qt-kit.git", repo_name: "drobbins-qt-kit", repo_owner: "funtoo-drobbins-src" }
    - { url: "https://github.com/funtoo-src/drobbins-steam-launcher.git", repo_name: "drobbins-steam-launcher", repo_owner: "funtoo-drobbins-src" }
    - { url: "https://github.com/funtoo-src/drobbins-subpop.git", repo_name: "drobbins-subpop", repo_owner: "funtoo-drobbins-src" }

  register: out
- debug: var=out.stdout_lines