- name: regen - ensure /etc/portage/patches/sys-apps/metatools patch folder exists
  file:
    path: /etc/portage/patches/sys-apps/metatools
    state: directory
    owner: root
    group: root
    mode: 0755
    recurse: yes
  register: out
- debug: var=out.stdout_lines

- name: regen - FL-12156 patch for metatools
  template:
    src: FL-12156.patch.j2
    dest: /etc/portage/patches/sys-apps/metatools/FL-12156.patch
    owner: root
    group: root
    mode: 0644
  register: out
- debug: var=out.stdout_lines
