---
- name: regen - ensure sync_base_url is in /etc/ego.conf
  ansible.builtin.lineinfile:
    path: /etc/ego.conf
    line: 'sync_base_url=https://github.com/funtoo-repo/{repo}'
    create: yes
    state: present
  register: out
- debug: var=out.stdout_lines

- name: regen - ensure GENTOO_MIRRORS is in /etc/portage/make.conf
  ansible.builtin.lineinfile:
    path: /etc/portage/make.conf
    line: 'GENTOO_MIRRORS=https://direct-github.funmore.org'
    create: yes
    state: present
  register: out
- debug: var=out.stdout_lines

- name: regen - ego sync
  shell: |
    /usr/bin/ego sync
  register: out
- debug: var=out.stdout_lines

- name: regen - ensure sys-apps/metatools is installed
  portage:
    package: sys-apps/metatools
    state: present
    quiet: true
  register: out
- debug: var=out.stdout_lines

- name: regen - ensure dev-python/jinja is installed
  portage:
    package: dev-python/jinja
    state: present
    quiet: true
  register: out
- debug: var=out.stdout_lines

- name: regen - ensure dev-python/pip  is installed
  portage:
    package: dev-python/pip
    state: present
    quiet: true
  register: out
- debug: var=out.stdout_lines

- name: regen - ensure dev-vcs/python-gitlab  is installed
  portage:
    package: dev-vcs/python-gitlab
    state: present
    quiet: true
  register: out
- debug: var=out.stdout_lines

- name: regen - ensure dev-python/pygments  is installed
  portage:
    package: dev-python/pygments
    state: present
    quiet: true
  register: out
- debug: var=out.stdout_lines

- name: metro - ensure sys-process/fcron is installed
  portage:
    package: sys-process/fcron
    state: present
    quiet: true
  register: out
- debug: var=out.stdout_lines
