---
- name: regen - ensure user tree exists
  user:
    name: "{{ regen_user }}"
    groups: portage
    append: yes
    generate_ssh_key: yes
    ssh_key_type: rsa
    ssh_key_bits: 4096
  register: out
- debug: var=out.stdout_lines

- name: regen - ssh authorized keys
  authorized_key:
    user: "{{ regen_user }}"
    state: present
    key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"

- name: regen - git config user name
  become: true
  become_user: "{{ regen_user }}"
  become_method: su
  become_flags: '--login'
  git_config:
    name: user.name
    scope: global
    value: "{{ regen_user }}"
  register: out
- debug: var=out.stdout_lines

- name: regen - git config user mail
  become: true
  become_user: "{{ regen_user }}"
  become_method: su
  become_flags: '--login'
  git_config:
    name: user.email
    scope: global
    value: "{{ regen_user }}@{{ container_name }}"
  register: out
- debug: var=out.stdout_lines

- name: regen - get ssh public key of {{ regen_user }}
  become: true
  become_user: "{{ regen_user }}"
  become_method: su
  become_flags: '--login'
  shell: cat ~/.ssh/id_rsa.pub
  register: public_key
- debug: var=public_key.stdout
- set_fact:
    "regen_ssh_public_key": "{{ public_key.stdout }}"